---
# example to adapt if you need to install a role from somewhere, usually Ansible Galaxy 
# from github
# - src: https://github.com/plone/ansible.plone_server.git
#   version: 1.3.8
#   name: plone.plone_server
# from galaxy
#- src: geerlingguy.java
